{% set name = "click-default-group-wheel" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/click-default-group-wheel-{{ version }}.tar.gz
  sha256: 1873fc3496669ef2492c31f4e512d87d93af26148eb383ebdf1b2b9971072519

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click
    - python >=3.6

test:
  imports:
    - click_default_group
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sublee/click-default-group/
  summary: Extends click.Group to invoke a command without explicit subcommand name (packaged as a wheel)
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
